### ISSUE TITLE
Fix Crashes

### ISSUE THREAD

**Issue by Fenius64** [SRB2-Mobile/SRB2-Android#12]
you need to fix some of the crashes that happen for no reason, they get so frustrating :
-Crash When Trying To Add Addons During An Ongoing Netgame
-Crash After Defeating A Boss/Completing An Act, the music slows down and fades away and the game crashes.

**Comment by Lactozilla** [comment]
What addons were you trying to add? Which Android version, phone model, etc.?

**Comment by Fenius64** [comment]
-What Addons Were You Trying To Add?
well sometimes the crashes happen even without addons but mostly they do with them, i usually add like character mods and lua mods, and rarely stage/gamemodes mods.
-Android Version
Android 11
-Phone Model
Galaxy A03
-RAM
4GB
lemme know if you need more info

**Comment by Fenius64** [comment]
is there any possibility of the crashes being fixed? it also happened for others, it happened to alot of people

**Comment by Lactozilla** [comment]
Yes

**Comment by Fenius64** [comment]
thank you man, you are the best

**Comment by Fenius64** [comment]
thank you man, you are the best

**Comment by Fenius64** [comment]
alright so apparently i found a crash log for this, this happened after i defeated boss (it happened in netplay but also happens in singleplayer too)
anyways here's crash log:
WARNING:€ LUA PANIC! bad argument #1 to '?' (string expected, got nil)
…ERROR:€ LUA PANIC! bad argument #1 to '?' (string expected, got nil)

I_Error(): An unfortunate Lua processing error occurred in the exe itself. This is not a scripting error on your part.
Removing this server from the master server...
HMS: connecting 'https://mb.srb2.org/MS/0/servers/257384/unlist'...

I_Error(): Tried to transmit to another node
I_ShutdownGraphics(): shut down
Shutting down joy system
I_Joystick: SDL's Joystick system has been shutdown
I_ShutdownTcpDriver: shut down
I_ShutdownGraphics(): graphics never started
I_ShutdownTcpDriver: shut down
I_ShutdownSystem(): end of logstream.
i have the log file aswell, please... push an update to fix this, please.
[latest-log.txt](https://github.com/SRB2-Mobile/SRB2-Android/files/9795382/latest-log.txt)
