### ISSUE TITLE
branch:android-port-next changing camera with touch screen does not work

### ISSUE THREAD

**Issue by bitten2up** [SRB2-Mobile/SRB2-Android#15]
you are unable to use the screen to move the camera, dont know if this was intended or not

**Comment by edotdot** [comment]
Cannot seem to reproduce this anymore. Maybe it is fixed?

**Comment by bitten2up** [comment]
> Cannot seem to reproduce this anymore. Maybe it is fixed?

it is fixed for some people, when gamepad refactor was removed, thats when i was fixed for me, but for other people they had to go and set mouse input to off
![image](https://github.com/SRB2-Mobile/SRB2-Android/assets/55027142/99bf809a-104a-4caf-99da-d1365700dc8c)
