### ISSUE TITLE
[2.2.11] 32-bit device startup crash

### ISSUE THREAD

**Issue by NicholasRickys** [SRB2-Mobile/SRB2-Android#19]
Nothing else really, it shows the splash screen and then crashes.

Sonic Robo Blast 2 for Android
Logfile: /storage/emulated/0/Sonic Robo Blast 2/logs/log-2023-05-21_17-36-28.txt
Setting up SRB2...

Sonic Robo Blast 2
Copyright (C) 1998-2023 by Sonic Team Junior

This program comes with ABSOLUTELY NO WARRANTY.

This is free software, and you are welcome to redistribute it
and/or modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2 of
the License, or (at your option) any later version.
See the 'LICENSE.txt' file for details.

Sonic the Hedgehog and related characters are trademarks of SEGA.
We do not claim ownership of SEGA's intellectual property used
in this program.

M_StartupLocale...
Looking for WADs in: Shared storage: /storage/emulated/0/Sonic Robo Blast 2App-specific storage: /storage/emulated/0/Android/data/org.stjr.srb2/files
Z_Init(): Init zone memory allocation daemon. 
System memory: 976MB - Free: 239MB
I_InitializeTime()...
W_UnpackMultipleFiles(): Unpacking IWAD and main PWADs.
W_InitMultipleFiles(): Adding IWAD and main PWADs.
Added file /storage/emulated/0/Android/data/org.stjr.srb2/files/srb2.pk3 (12647 lumps)
Loading SOC from /storage/emulated/0/Android/data/org.stjr.srb2/files/srb2.pk3|SOC/SOC_TITL
Loading SOC from /storage/emulated/0/Android/data/org.stjr.srb2/files/srb2.pk3|SOC/SOC_LETR
Added file zones.pk3 (141 lumps)
Loading SOC from zones.pk3|SOC/SOC_EMBM.txt
Loading SOC from zones.pk3|SOC/SOC_HEAD.txt
Loading SOC from zones.pk3|SOC/SOC_SECR.txt
Loading SOC from zones.pk3|SOC/Tutorial.txt
Added file /storage/emulated/0/Android/data/org.stjr.srb2/files/player.dta (1869 lumps)
Loading SOC from /storage/emulated/0/Android/data/org.stjr.srb2/files/player.dta|SOC_PLAY
Added file /storage/emulated/0/Android/data/org.stjr.srb2/files/patch.pk3 (14 lumps)
Added file android.pk3 (255 lumps)
Loading SOC from android.pk3|SOC/Titlescreen.soc
Added file music.dta (181 lumps)
I_StartupGraphics()...
�Current Video Mode
 1024x600 at 32 bit color
 Stored in system memory
CPU Info: 486: 0, 586: 0, MMX: 0, 3DNow: 0, MMXExt: 0, SSE2: 0

Process killed by signal: SIGSEGV - segment violation

**Comment by Saafork** [comment]
Happens on my device too. Hope it gets patched

**Comment by george2781** [comment]
Same issue, latest-log.txt is pretty much if not entirely identical to that of OP, ending in SIGSEGV
Here's hoping the maintainer(s) of this repo get around to fixing this.

**Comment by Saafork** [comment]
The patch has appeared to have been released, as other threads about this has been closed

**Comment by bitten2up** [comment]
can you try #37 and inform me if it works

**Comment by edotdot** [comment]
32-bit crash fixed as of d1100bd39c799ec4d2b561790b500dbbd9526e53
