### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by sonicyt1234** [SRB2-Mobile/SRB2-Android#21]
I have an Android 13, and even though I accepted all permissions, it doesn't work

**Comment by NicholasRickys** [comment]
you have a 32 bit device, unless u know C you cant really do anything other than waiting for a patch to release

**Comment by sonicyt1234** [comment]
I actually have the most high-tech tablet right now

**Comment by NicholasRickys** [comment]
are you sure is arm64?

**Comment by sonicyt1234** [comment]
Yes.

**Comment by Ralph-Jeremy65** [comment]
For whatever reason, some fresh installs of v2.2.11 Android doesn't go to the unpacking process and just sigsegvs before the green bar and the splash screen appears:

Sonic Robo Blast 2 for Android
Logfile: /storage/emulated/0/Sonic Robo Blast 2/logs/log-2023-05-22_10-53-06.txt
Setting up SRB2...


Sonic Robo Blast 2
Copyright (C) 1998-2023 by Sonic Team Junior

This program comes with ABSOLUTELY NO WARRANTY.

This is free software, and you are welcome to redistribute it
and/or modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2 of
the License, or (at your option) any later version.
See the 'LICENSE.txt' file for details.

Sonic the Hedgehog and related characters are trademarks of SEGA.
We do not claim ownership of SEGA's intellectual property used
in this program.

M_StartupLocale...

Process killed by signal: SIGSEGV - segment violation

**Comment by NicholasRickys** [comment]
this is a rather weird issue, maybe we can extract the assets ourselves?

**Comment by NicholasRickys** [comment]
just tried it, no luck

It already extracts the srb2.pk3, patch.pk3, and player.dta files

**Comment by Ralph-Jeremy65** [comment]
Until there's an official patch, I think I have a little trick for that
[Sonic_Robo_Blast_2.zip](https://github.com/SRB2-Mobile/SRB2-Android/files/11527146/Sonic_Robo_Blast_2.zip)

**Comment by NicholasRickys** [comment]
tested this too, doesnt work

**Comment by Ralph-Jeremy65** [comment]
huh

**Comment by ffoxD** [comment]
I have a 64 bit device, I have extracted the assets myself, and I still experience the issue. The prereleases and 2.2.10 worked fine.

**Comment by ffoxD** [comment]
![Screenshot_2023-05-22-10-44-57-499_ru andr7e deviceinfohw](https://github.com/SRB2-Mobile/SRB2-Android/assets/67541651/95e250d2-73bf-413e-a4fc-88cf4391ec69)
![Screenshot_2023-05-22-10-45-07-403_ru andr7e deviceinfohw](https://github.com/SRB2-Mobile/SRB2-Android/assets/67541651/8321ba95-9846-4947-bab8-cd23bc3ee2d8)
![Screenshot_2023-05-22-10-45-11-643_ru andr7e deviceinfohw](https://github.com/SRB2-Mobile/SRB2-Android/assets/67541651/e9cfeaee-e43c-4098-a60a-ab31404fd672)
Also have information about my device, might be useful

**Comment by bitten2up** [comment]
> I have a 64 bit device, I have extracted the assets myself, and I still experience the issue. The prereleases and 2.2.10 worked fine.

if the prereleases worked for you give me a sec to merge 2.2.11 off of that real quick

**Comment by xsm2** [comment]
The only issue I see with that build from what I tested is that the use "native resolution" option does not work correctly (it picks 2160x1080 when my device's resolution is 2400x1080 which means I have black bars at the side of the screen)

**Comment by xsm2** [comment]
There is also an issue with touch controls: the "logical buttons" are not located where is shown in the screen when the aspect ration does not match the screen aspect ratio. 

It applies to menu options, confirm and cancel buttons and also to the virtual touch pad.

From my testing the problem, it's like if the "visual buttons" position scaled with resolution/aspect ratio but the "logical buttons" didn't. You can see the problem easily by changing the resolution to a 4:3 one, when you press a button they do not work, instead if you press where the button was located before the resolution change it does work.

 I don't open a new issues for this problems because I don't know if is a specific problem from this build or if happened in the other one too as it crashed for me.

**Comment by twanye** [comment]
I have the same problem

**Comment by twanye** [comment]
I have android 13 too. My phone is a Samsung  Galaxy s21 Fe 5G

**Comment by bitten2up** [comment]
> From my testing, it's like if the "visual buttons" position scale with resolution/aspect ratio but the "logical buttons" don't. You can see the problem easily by changing the resolution to a 4:3 one, when you press any button it does not work, instead if you press where the button was located before the resolution change it does work.
 ah that makes sense, tho it was just meant to be a quick fix

**Comment by twanye** [comment]
No the crash thing

**Comment by twanye** [comment]
No the crash thing

**Comment by twanye** [comment]
What the entire issue is about

**Comment by bitten2up** [comment]
> No the crash thing

oops i ment to say something else, it's most likely because the video is being stretched or smth like that

**Comment by sonicyt1234** [comment]
Surprisingly, bitten2up's version seems to work perfectly on my device

**Comment by twanye** [comment]
I'ma try that then

**Comment by twanye** [comment]
I have a Chromebook also

**Comment by twanye** [comment]
2.2.10 worked right

**Comment by Ultramanikpl2022** [comment]
Ever after patch 1 still not works

**Comment by yipeeXDw** [comment]
> Well 2.2.11 is unfixable

True

**Comment by bitten2up** [comment]
can you try #37 and inform me if it works

**Comment by edotdot** [comment]
32-bit crash fixed as of d1100bd39c799ec4d2b561790b500dbbd9526e53
