### ISSUE TITLE
Models COMPLETELY glitched on SRB2.

### ISSUE THREAD

**Issue by Stormisred88** [SRB2-Mobile/SRB2-Android#23]
Hi there, whenever I first booted up the new version of SRB2 android, and turned on OpenGL to use the 3D Models, the textures were completely glitched on the characters and the other things, I don't know if it's on my end or for everyone else.

**Comment by AndrewtheAndroiduser** [comment]
This is happening with me too for some reason it uses the danos sonic textures on my pointy model

**Comment by Stormisred88** [comment]
> This is happening with me too for some reason it uses the danos sonic textures on my pointy model even though I never installed danos

Glad to see i'm not the only one.

**Comment by NicholasRickys** [comment]
you should probably try making use of the modelpack feature

**Comment by Stormisred88** [comment]
I'll give that a try.

**Comment by Stormisred88** [comment]
> you should probably try making use of the modelpack feature

I'll give that a try.

**Comment by AndrewtheAndroiduser** [comment]
> you should probably try making use of the modelpack feature

I tried modelpack AJsPack.zip and it just turned everything back into sprites

**Comment by NicholasRickys** [comment]
> > you should probably try making use of the modelpack feature
> 
> I tried "modelpack AJsPack.zip" (AJ being me), and it just turned everything back into sprites unless if the zip is in the wrong folder I'm sure that that shouldn't happen

you should check how the default model pack is formatted

if it still doesn't work, make sure to look how is laid out

**Comment by AndrewtheAndroiduser** [comment]
> > > you should probably try making use of the modelpack feature
> > 
> > 
> > I tried "modelpack AJsPack.zip" (AJ being me), and it just turned everything back into sprites unless if the zip is in the wrong folder I'm sure that that shouldn't happen
> 
> you should check how the default model pack zip is formatted
> 
> if it still doesn't work, make sure to look how is laid out

There's a default?! I started with no model pack

**Comment by bitten2up** [comment]
hmm it should be in https://github.com/SRB2-Mobile/SRB2-Android/tree/android-port-next/android/app/src/main/assets, but it seems to be removed

**Comment by shaweek13** [comment]
yep all models are completely broken or just won't load :/

**Comment by AndrewtheAndroiduser** [comment]
> > you should probably try making use of the modelpack feature
> 
> I tried "modelpack AJsPack.zip" (AJ being me), and it just turned everything back into sprites unless if the zip is in the wrong folder I'm sure that that shouldn't happen

So I found the problem my models.dat is very much spaghetti code
