### ISSUE TITLE
App not working after 2.2.11:(

### ISSUE THREAD

**Issue by Zein995** [SRB2-Mobile/SRB2-Android#24]
After I update srb to 2.2.11, I can't play it. After I open app I see "sonic team Jr" logo and after 15 second app automatically close. I don't know if it's a  bug or not, but if you can fix this I'm can be happy again. :)

P.S.- sorry for my bad english

**Comment by Ralph-Jeremy65** [comment]
#19

**Comment by Adangame** [comment]
O cara quando eu abro o jogo fecha conseta pls

**Comment by bitten2up** [comment]
try https://app.bitten2up.dev/working/2211-arm64/srb2.apk

**Comment by Foxbow85** [comment]
The link Doesn't Work, I have the same issue, Running on Samsung Galaxy A13.

**Comment by Greyzin** [comment]
> try https://app.bitten2up.dev/working/2211-arm64/srb2.apk

Do you have a version that can run 32-bit cell phones?  (Me and I think other people also hand have a 64-bit cell phone)

**Comment by NeobobYT** [comment]
My phone "LG Q60" not work the apk i open the app and crashes for 15 seconds and my phone is 32bits 
PD: my inglish is very bad

**Comment by Foxbow85** [comment]
Turns out I have a 32-bit phone.

**Comment by bitten2up** [comment]
ok got 32 bit partually working #37

**Comment by Arthur3911** [comment]
O meu celular e o Galaxy a10 e o srb2 não está funcionando,oque eu Faso?

**Comment by bitten2up** [comment]
> My cell phone is Galaxy a10 and srb2 is not working, what do I do?
> ok got 32 bit partually working [#37 ](https://github.com/SRB2-Mobile/SRB2-Android/pull/37)

**Comment by ru-afk** [comment]
Same

**Comment by ru-afk** [comment]
I got a galaxy  A13 but the link don't work

**Comment by bitten2up** [comment]
> I got a galaxy A13 but the link don't work

server is down for now, you can check the gh actions an this repo for a no assets build
