### ISSUE TITLE
Models pack not working on 2.2.11 Patch 1

### ISSUE THREAD

**Issue by xsm2** [SRB2-Mobile/SRB2-Android#26]
I have a model pack in the "Sonic Robo Blast 2" folder but when I type the command 'modelspack "models.zip"' the console output is 'Unknown command "modelspack"'

**Comment by montydoesgames** [comment]
It's "modelpack"

**Comment by xsm2** [comment]
Yeah, "modelpack" command it's working, but thats not the command that appears on the 2.2.11 release notes. Also it would be nice if specific commands for the android port would appear somewhere, like the readme.md.

Anyway, even if now the command is recognized, it's still not working, the error now is "Error while loading model definition file: could not open file models.dat".

The zip does not have password and decompresion works fine. I have tried to compress the zip twice, one with winrar and another one with nanazip (a 7zip fork). It's a models.dat that I use without problems in the windows version of srb2.

**Comment by xsm2** [comment]
I have done a little bit more testing and I'm not able to make it work, I'not even able to use the command 'modelpack "modelpacks/default.zip"' which if I understand the code from here correctly it's the default model pack, it gives me exactly the same error as above: "Error while loading model definition file: could not open file models.dat"

https://github.com/SRB2-Mobile/SRB2-Android/blob/786a3296469b30587ba7422292ae053dbc4cd2db/src/hardware/hw_main.c#L6530

Another thing I have realised is that if you write in the command the name of a file that doesn't exists (I had a typo when testing) it doesn't throw any error and the default models stop showing too.

**Comment by abdogm** [comment]
3D model pack is working 
kinda
im i doing something wrong ?
it was tested on 64 bit device 
![Screenshot_2023-06-02-12-55-04-062_org stjr srb2](https://github.com/SRB2-Mobile/SRB2-Android/assets/72724405/f5afa0a9-44f8-4232-8479-c463fe2b5e05)

**Comment by xsm2** [comment]
I think have found a bug related to this but I'm not sure if it will fix the models. In this line: 

https://github.com/SRB2-Mobile/SRB2-Android/blob/786a3296469b30587ba7422292ae053dbc4cd2db/src/hardware/hw_md2.c#L379

The file mode should be 'r' and not 'rb', 'rb' is for reading binary files and the models.dat is a text file

**Comment by xsm2** [comment]
I tried again to use 'modelpack "modelpacks/default.zip"' and it did work correctly after using it twice (the first time failed again), at least I can use the default modelpack again. 

![imagen](https://github.com/SRB2-Mobile/SRB2-Android/assets/32161135/ae18df8b-e768-4ca1-b7c0-c12c556a7aaa)

**Comment by shaweek13** [comment]
yea and the vdlc just don't work

**Comment by AOSrb2** [comment]
Help I don't have models aswell

**Comment by juanjosesolercastro** [comment]
How to get Jeck Jims models

**Comment by juanjosesolercastro** [comment]
How to get the Jeck Jims models

**Comment by xsm2** [comment]
> Help I don't have models aswell

> How to get the Jeck Jims models

Github issues should not be the place to ask for help, but to report issues. Go to srb2 discord server and ask for help there as there is a dedicate channel for that (#android-help). 

That said I write this in hopes the spam of the issues/comments stops (it won't): You can't copy the models.dat and the models folder in these releases (2.2.11 and 2.2.11 patch 1), it won't work, if you have done that delete them, you have to use the models pack feature to change models.

Instructions on how to use model packs are in the [2.2.11 release notes](https://github.com/SRB2-Mobile/SRB2-Android/releases/tag/android-port-build-v2211). If it doesn't work for you, you can go back to the default model pack with this command: `modelpack "modelpacks/default.zip"` (you may have to use it twice in a row to make it work), that should restore the default models.

Only comment on this issue after solving any doubt you have in the srb2 discord, if you have tried to correctly use the models pack, and if you can add something helpful to the conversation, like maybe if the pack works does/doesn't work for you and your phone model and android version to see if we can find why modelpacks work for some people but not for others.

**Comment by juanjosesolercastro** [comment]
Shit

**Comment by juanjosesolercastro** [comment]
Áre you stupid

**Comment by bitten2up** [comment]
> I think have found a bug related to this but I'm not sure if it will fix the models. In this line:
> 
> https://github.com/SRB2-Mobile/SRB2-Android/blob/786a3296469b30587ba7422292ae053dbc4cd2db/src/hardware/hw_md2.c#L379
> 
> The file mode should be 'r' and not 'rb', 'rb' is for reading binary files and the models.dat is a text file

should be fine its all data, running it through a debugger it seems to crash when loading the md3

**Comment by hedgehog67** [comment]
![Screenshot_20230803-190749_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/9bba9edd-6659-48c9-99a7-8a7a205adc22)

**Comment by saa148** [comment]
I found that you change the default model pack in the game it will run. I have tested this with Jeck Jim's models.

**Comment by bitten2up** [comment]
i have figured it out, forgot to post it here, here is what i posted in the discord and it should work for most cases:

## disclaimer

i will **NOT** provide any modelpack ready zips, unless like the creator gives me permission for some fucking reason. make them yourself, im not going to be an asshole to the creator because someone finds it to difficult to make it yourself. im just getting this out of the way before someone asks me to do this, but despite this rant someone will inevitably ask me anyways but hopefully this will prevent most people who see this from asking

## now how to do this

how to use modelpacks for peppermint aka the one that has been asked the most:
1. download the modelpack
2. move the zip to a new empty folder
3. extract the zip
4. use some kind of text editor to create a `models.dat` folder and put everything above `------------- Put theese into your models.dat file -------------` from `Read Please!.txt` into the `models.dat` file mentioned earlier
5. create a `models` folder and move the `PEPPERMODELS` into it
6. select the `models` folder and the `models.dat` and compress them into a zip file

when you are all done your zip file should look like this![Screenshot_20230726_183533_Files.jpg](https://github.com/SRB2-Mobile/SRB2-Android/assets/55027142/0d393d6d-dc86-4991-b3bc-5110a008cc5f)

7. move your zip to the to your srb2 folder and run the `modelpack <file.zip>` command in srb2

**Comment by xsm2** [comment]
> i have figured it out, forgot to post it here, here is what i posted in the discord and it should work for most cases, also note this - is based on the lastest android-port commit:
> ## disclaimer
> 
> i will **NOT** provide any modelpack ready zips, unless like the creator gives me permission for some reason. make them yourself, im not going to be an asshole to the creator because someone finds it to difficult to make it yourself. im just getting this out of the way before someone asks me to do this, but despite this rant someone will inevitably ask me anyways but hopefully this will prevent most people who see this from asking
> ## now how to do this
> 
> how to use modelpacks for peppermint aka the one that has been asked the most:
> 
>     1. download the modelpack
> 
>     2. move the zip to a new empty folder
> 
>     3. extract the zip
> 
>     4. use some kind of text editor to create a `models.dat` folder and put everything above `------------- Put theese into your models.dat file -------------` from `Read Please!.txt` into the `models.dat` file mentioned earlier
> 
>     5. create a `models` folder and move the `PEPPERMODELS` into it
> 
>     6. select the `models` folder and the `models.dat` and compress them into a zip file
> 
> 
> when you are all done your zip file should look like this![Screenshot_20230726_183533_Files.jpg](https://user-images.githubusercontent.com/55027142/260067974-0d393d6d-dc86-4991-b3bc-5110a008cc5f.jpg)
> 
>     7. move your zip to the to your srb2 folder and run the `modelpack <file.zip>` command in srb2

I have done that more than once, but it does not work for me. I know there are people who said it works, it's not my case.

**Comment by bitten2up** [comment]
> > i have figured it out, forgot to post it here, here is what i posted in the discord and it should work for most cases, also note this - is based on the lastest android-port commit:
> > ## disclaimer
> > i will **NOT** provide any modelpack ready zips, unless like the creator gives me permission for some reason. make them yourself, im not going to be an asshole to the creator because someone finds it to difficult to make it yourself. im just getting this out of the way before someone asks me to do this, but despite this rant someone will inevitably ask me anyways but hopefully this will prevent most people who see this from asking
> > ## now how to do this
> > how to use modelpacks for peppermint aka the one that has been asked the most:
> > ```
> > 1. download the modelpack
> > 
> > 2. move the zip to a new empty folder
> > 
> > 3. extract the zip
> > 
> > 4. use some kind of text editor to create a `models.dat` folder and put everything above `------------- Put theese into your models.dat file -------------` from `Read Please!.txt` into the `models.dat` file mentioned earlier
> > 
> > 5. create a `models` folder and move the `PEPPERMODELS` into it
> > 
> > 6. select the `models` folder and the `models.dat` and compress them into a zip file
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when you are all done your zip file should look like this![Screenshot_20230726_183533_Files.jpg](https://user-images.githubusercontent.com/55027142/260067974-0d393d6d-dc86-4991-b3bc-5110a008cc5f.jpg)
> > ```
> > 7. move your zip to the to your srb2 folder and run the `modelpack <file.zip>` command in srb2
> > ```
> 
> I have done that more than once, but it does not work for me. I know there are people who said it works, it's not my case.

are you using the latest actions build?
