### ISSUE TITLE
The game keeps crashing

### ISSUE THREAD

**Issue by ChrisLes324** [SRB2-Mobile/SRB2-Android#30]
I have a problem, it keeps crashing and doesn't show the green bar (i know that v11 got patched), can you really fix that please?, And if it's already fixed, can you do a 32 bit version?

**Comment by Zein995** [comment]
I still have a same problem

**Comment by fil52317634343** [comment]
Me too PLZ Fix this bug

**Comment by yipeeXDw** [comment]
I agree with this guy we need a 32 bits version right now

**Comment by bitten2up** [comment]
can you try #37 and inform me if it works

**Comment by ChrisLes324** [comment]
I tried it and it works!, The only problem i got it's the lag.
But today i was playing it normally and a screen appeared saying "Carrier Services keeps not working" and my phone crashed, i will never play again srb2 on Android if it keeps doing that

**Comment by bitten2up** [comment]
> I tried it and it works!, The only problem i got it's the lag. But today i was playing it normally and a screen appeared saying "Carrier Services keeps not working" and my phone crashed, i will never play again srb2 on Android if it keeps doing that

yeah that probally was a coincident, it should be good

**Comment by edotdot** [comment]
32-bit crash fixed as of d1100bd39c799ec4d2b561790b500dbbd9526e53
