### ISSUE TITLE
Srb2 2.2.11 32 bits version

### ISSUE THREAD

**Issue by yipeeXDw** [SRB2-Mobile/SRB2-Android#31]
The game crashes on 32 bits devices like mine so please sonic team JR

**Comment by bitten2up** [comment]
can you try #37 and inform me if it works

**Comment by yipeeXDw** [comment]
Alright ser you later

**Comment by yipeeXDw** [comment]
> can you try #37 and inform me if it works

YES IT WORKS THANKS

**Comment by yipeeXDw** [comment]
> can you try #37 and inform me if it works

And now the problem is how do i put My model pack

**Comment by yipeeXDw** [comment]
> > can you try #37 and inform me if it works
> 
> And now the problem is how do i put My model pack

Si you're not gonna say anything?

**Comment by bitten2up** [comment]
no because im not fucking working on fixing the modelpacks, they are broken

**Comment by yipeeXDw** [comment]
> no because im not fucking working on fixing the modelpacks, they are broken even on 64 bit devices


https://github.com/SRB2-Mobile/SRB2-Android/assets/130852521/576c6b92-8124-4c32-b81a-2239f629a36c

**Comment by yipeeXDw** [comment]
> no because im not fucking working on fixing the modelpacks, they are broken even on 64 bit devices

I guess i have to move to 2.2.10

**Comment by yipeeXDw** [comment]
Again

**Comment by yipeeXDw** [comment]
> no because im not fucking working on fixing the modelpacks, they are broken even on 64 bit devices

Hey dude i just figure out how to fix then, just move the model files to the srb2 folder (android/data/org.stjr.srb2/files) the only bad thing is that the addon models doesn't work but pretty cool

**Comment by edotdot** [comment]
32-bit crash fixed as of d1100bd39c799ec4d2b561790b500dbbd9526e53
