### ISSUE TITLE
Opengl is not working

### ISSUE THREAD

**Issue by Jolijolu** [SRB2-Mobile/SRB2-Android#33]
When i use opengl the control's become weird and i can't use some buttons and the models glitch!

**Comment by Jolijolu** [comment]
![Screenshot_2023-06-15-13-52-00-714_org stjr srb2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136224665/dc3320d7-fe3f-4a00-b05d-e5d2d535756c)

**Comment by Jolijolu** [comment]
![Uploading Screenshot_2023-06-15-13-52-00-714_org.stjr.srb2.jpg…]()

**Comment by Jolijolu** [comment]
![Screenshot_2023-06-15-13-52-00-714_org stjr srb2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136224665/956403c8-caae-430f-ab63-192e9333b0ff)

**Comment by sSonicGamer** [comment]
Its bug here:
Error : missing central directory

Error :while downloading model definition could not open model.dat

**Comment by sSonicGamer** [comment]
Its bug that doesn't work to modelpacks
