### ISSUE TITLE
Crashes on the SRB2Jr. boot-screen

### ISSUE THREAD

**Issue by usermodprogram1780** [SRB2-Mobile/SRB2-Android#35]
The game crashes in the "Sonic Team Jr. presents" screen approximately 30s after the game is launched and it quits by itself after that.

More details:
-Device: LG K22+
-RAM: 3GB
-CPU: Qualcomm QM215 Snapdragon 215 (Quad-core 1.3 GHz Cortex-A53)
-GPU: Adreno 308
-OS: Android 10
-ROM: 64GB

**Comment by bitten2up** [comment]
can you try #37 and inform me if it works

**Comment by edotdot** [comment]
Fixed in d1100bd39c799ec4d2b561790b500dbbd9526e53
