### ISSUE TITLE
Вылетает игра при входе Сделайте для 32 бит

### ISSUE THREAD

**Issue by Robot20Fox10Dragon30** [SRB2-Mobile/SRB2-Android#36]
Пожалуйста сделайте для 32 бит

**Comment by bitten2up** [comment]
im just going to translate this rq:
## please make it for 32 bit

while it should be working on 32 bit as it is set it to compile for 32 bits as well, it doesn't seem to work based on various reports, and my own testing by setting it to only compile for 32bit, im sure that @Lactozilla  and @edotdot are working on it

and im gonna translate this into rusian using google translate rq:

хотя он должен работать на 32-битной версии, поскольку он настроен на компиляцию и для 32-битной версии, похоже, он не работает на основе различных отчетов и моего собственного тестирования, установив его для компиляции только для 32-битной версии, я уверен, что @ Lactozilla и @edotdot работают над этим.

**Comment by Robot20Fox10Dragon30** [comment]
Ok

**Comment by Robot20Fox10Dragon30** [comment]
Спасибо что на Русский перевели

**Comment by bitten2up** [comment]
#37
nm im working on it now apperently
