### ISSUE TITLE
The mods models in srb2 v11 Android port are strange

### ISSUE THREAD

**Issue by Rafanimatronic** [SRB2-Mobile/SRB2-Android#39]
I dowload the version 11 from srb2 in my android and the models stayed like this can someone explain to me how to solve it?

![Screenshot_2023-06-17-22-20-48-639_org stjr srb2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136941062/43dcada3-f766-4306-8965-8632b4f93544)

**Comment by hedgehog67** [comment]
Mine is also like this I think I should never update the game to 2.2.11..

**Comment by hedgehog67** [comment]
![Screenshot_20230618-093903_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/40c6508f-3868-4d0b-9e74-8a5af8c1e4e8)

**Comment by hedgehog67** [comment]
I'm like modern sonic now

**Comment by hedgehog67** [comment]
Even the command is not working anymore so goodbye 3d models

**Comment by hedgehog67** [comment]
![Picsart_23-06-18_10-00-34-139](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/dbfd1de9-e349-4dab-9518-991f023de5da)

**Comment by Rafanimatronic** [comment]
Rip models :(

**Comment by hedgehog67** [comment]
E triste:(

**Comment by hedgehog67** [comment]
At least I have my second form of 3d models but it's not as good

**Comment by hedgehog67** [comment]
![Uploading Screenshot_20230623-183945_Sonic Robo Blast 2.jpg…]()

**Comment by hedgehog67** [comment]
![Uploading Screenshot_20230623-183945_Sonic Robo Blast 2.png…]()

**Comment by hedgehog67** [comment]
![Uploading srb20001.png…]()

**Comment by hedgehog67** [comment]
![Uploading srb20001.png…]()

**Comment by hedgehog67** [comment]
![Screenshot_20230623-183945_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/9dd7e806-d828-4e29-8026-812bd10d69f1)

**Comment by hedgehog67** [comment]
And that's exactly what you're seeing

**Comment by hedgehog67** [comment]
But for some reason I still manage to put the md3 from altsonic and replace the sonic md3 with the one from alt sonic

**Comment by hedgehog67** [comment]
![srb20002](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/93692e52-723b-4b35-a2e1-bebffc3027a1)

**Comment by hedgehog67** [comment]
In my opinion I think it's because the model is the same but with different animations.

**Comment by hedgehog67** [comment]
But Sonic Junior team if you're seeing this don't fix it otherwise I don't choose anymore

**Comment by Rafanimatronic** [comment]
Wait you dont want the Sonic team junior to fix this bug?

**Comment by hedgehog67** [comment]
I'm not talking about alt sonic bug's md3

**Comment by hedgehog67** [comment]
Ai dos addons eu quero que consertem

**Comment by hedgehog67** [comment]
Oh yes, I want team sonic junior to fix only the addons models

**Comment by hedgehog67** [comment]
Warning if you want to change the sonic model just change it to alt sonic because peppermint models got buggy in my game so just change the md3 from sonic to alt sonic

**Comment by hedgehog67** [comment]
One more thing this is only for those who have alt sonic model

**Comment by hedgehog67** [comment]
Of course I want team sonic to fix this

**Comment by hedgehog67** [comment]
Mean team sonic junior

**Comment by hedgehog67** [comment]
This is me when they destroyed the addons 3d models

**Comment by hedgehog67** [comment]
![srb20004](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/75742a48-905a-4d04-b6c7-29a771c603de)

**Comment by hedgehog67** [comment]
In fact, I don't even know why I consider the sonic alt model working only in Sonic a bug._.

**Comment by hedgehog67** [comment]
For me like this bug of alt sonic model working on Sonic bug

**Comment by hedgehog67** [comment]
I like to change the sonic model to this one

**Comment by hedgehog67** [comment]
I had an idea I modified the models/textures looks fun to do this look at the result

**Comment by hedgehog67** [comment]
![srb20005](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/c4996a68-5831-44ec-a538-e3b0b1a367a6)

**Comment by hedgehog67** [comment]
I made tails wear blue shoes

**Comment by Rafanimatronic** [comment]
Oh ok i get It now

**Comment by Rafanimatronic** [comment]
how did you put the alt sonic model in the original sonic because when i put any model other than the one already in the original game it gets buggy

**Comment by hedgehog67** [comment]
I just said alt sonic only

**Comment by hedgehog67** [comment]
I'll explain to you first take the md3 from alt and rename it to SONIC.md3 then cut it to the default.zip folder then enter the PLAY folder

**Comment by hedgehog67** [comment]
Did you understand?

**Comment by hedgehog67** [comment]
I think I found out why it's buggy, it must be the amount of polygons because they use Jeck Jims models and in the past you had to put the models folder in Jeck Jims as it is a zip file

**Comment by hedgehog67** [comment]
You can no longer use this method

**Comment by hedgehog67** [comment]
You have to paste the md3 in PLAY From default.zip

**Comment by hedgehog67** [comment]
Now with the tails with blue shoes and the same you will get the blend and the texture rename both to TAILS.png and the blend to TAILS_blend.png cut and paste in the PLAY folder of the default.zip

**Comment by hedgehog67** [comment]
That's how I learned on my own

**Comment by Rafanimatronic** [comment]
Ok thanks

**Comment by hedgehog67** [comment]
You are welcome

**Comment by hedgehog67** [comment]
They work perfectly in multiplayer

**Comment by Rafanimatronic** [comment]
I cant find the default.zip archive

**Comment by hedgehog67** [comment]
See the gameplay of me playing your game can look like this

**Comment by hedgehog67** [comment]
Oh

**Comment by hedgehog67** [comment]
Did you go to the modelpacks Folder?

**Comment by hedgehog67** [comment]
Because that's where default.zip will be

**Comment by Rafanimatronic** [comment]
Like the models folder? I need to chance the name?

**Comment by Rafanimatronic** [comment]
Change

**Comment by Rafanimatronic** [comment]
I dont have this folder

**Comment by hedgehog67** [comment]
![Screenshot_20230624-123845_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/250b73d3-0476-4185-8f19-4aec5c9e2a1b)

**Comment by hedgehog67** [comment]
![Screenshot_20230624-123854_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/ee9fa62d-f0ac-4fdd-b739-13ea96893f39)

**Comment by hedgehog67** [comment]
![Screenshot_20230624-123834_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/81133c36-35a6-4d4d-a5ec-dd123d1585c3)

**Comment by hedgehog67** [comment]
![Screenshot_20230624-123902_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/5d06d4d9-4846-4311-81a9-ef9200cffcea)

**Comment by hedgehog67** [comment]
![Screenshot_20230624-123910_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/3902f7cf-9ed1-4053-8d74-1c82b0468f96)

**Comment by hedgehog67** [comment]
![Screenshot_20230624-123925_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/8dfc1176-4b3f-49f0-9ef9-4688598f00ef)

**Comment by Rafanimatronic** [comment]
![Screenshot_2023-06-24-12-42-21-362_ru zdevs zarchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136941062/68c0b143-c337-4911-a4f1-296a8167d686)

**Comment by Rafanimatronic** [comment]
![Screenshot_2023-06-24-12-42-30-384_ru zdevs zarchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136941062/dfd53545-3762-42d6-8e4b-ba972db7251c)

**Comment by Rafanimatronic** [comment]
![Screenshot_2023-06-24-12-42-36-601_ru zdevs zarchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136941062/d7b6141d-b924-47e0-b6ea-07670b2266bb)

**Comment by hedgehog67** [comment]
;)

**Comment by Rafanimatronic** [comment]
Eu só tenho esses tres arquivos

**Comment by hedgehog67** [comment]
I forgot to tell you

**Comment by hedgehog67** [comment]
![Screenshot_20230624-124450_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/7498c12a-071e-4c5c-af2f-2ef75966fa25)

**Comment by hedgehog67** [comment]
![Screenshot_20230624-124500_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/51ea5392-fa1d-46e0-bae1-3a3840e3e80a)

**Comment by hedgehog67** [comment]
Press on the Second one

**Comment by hedgehog67** [comment]
![Screenshot_20230624-124510_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/013c35a6-df02-40af-b8d2-b92d43569d33)

**Comment by hedgehog67** [comment]
Press assets

**Comment by hedgehog67** [comment]
![Screenshot_20230624-124521_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/bd360494-2bb5-4889-b7c4-5f7041fdaa2c)

**Comment by hedgehog67** [comment]
copy all

**Comment by hedgehog67** [comment]
![Screenshot_20230624-124539_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/7c56195f-583a-42d0-88f0-7fd12ea07786)
![Screenshot_20230624-124559_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/c6774c35-70c7-4e72-88dd-b2c50b502d50)
![Screenshot_20230624-124610_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/9194bf40-8cd3-4b77-9d62-4739db6ea3d4)
![Screenshot_20230624-124548_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/14a68f12-e074-487f-817b-3c92bc66f776)

**Comment by hedgehog67** [comment]
Then paste all

**Comment by hedgehog67** [comment]
Also forget about the last photo It does not count

**Comment by Rafanimatronic** [comment]
Ok i Will try

**Comment by hedgehog67** [comment]
It work?

**Comment by Rafanimatronic** [comment]
The game ignore the models

**Comment by hedgehog67** [comment]
Show me a screenshot

**Comment by hedgehog67** [comment]
About this

**Comment by Rafanimatronic** [comment]
![Uploading Screenshot_2023-06-24-13-37-32-122_org.stjr.srb2.jpg…]()

**Comment by Rafanimatronic** [comment]
![Screenshot_2023-06-24-13-37-32-122_org stjr srb2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136941062/11c52123-71ec-42b3-be39-57b3759a277f)

**Comment by hedgehog67** [comment]
Oh

**Comment by hedgehog67** [comment]
I don't know fix it but now you can have the sonic alt model instead of the original sonic and tails with blueshoes

**Comment by hedgehog67** [comment]
Because this is definitely normal to happen

**Comment by hedgehog67** [comment]
For now

**Comment by hedgehog67** [comment]
![Screenshot_20230624-134836_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/e99da01f-87cd-47eb-befe-9b2658555213)

**Comment by Rafanimatronic** [comment]
ok now the only thing we can do is be patient and wait for the second patch

**Comment by hedgehog67** [comment]
Can i make a question?

**Comment by hedgehog67** [comment]
I found this tutorial on YouTube but I don't know if it works

**Comment by hedgehog67** [comment]
https://www.youtube.com/watch?v=liNu-pmJolE

**Comment by Rafanimatronic** [comment]
The comments of this vídeo Tells everything

**Comment by hedgehog67** [comment]
Oh

**Comment by hedgehog67** [comment]
And it did work?

**Comment by hedgehog67** [comment]
Consegui

**Comment by hedgehog67** [comment]
and support addons

**Comment by hedgehog67** [comment]
![Screenshot_20230713-084101_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/dec348e4-2ad2-4024-a3e9-ab3c8b2a87b9)
![Screenshot_20230713-084500_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/110e4563-2440-41bc-8d41-2bd3e0c7e019)

**Comment by hedgehog67** [comment]
E não e edição

**Comment by hedgehog67** [comment]
![Screenshot_20230714-092145_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/064c8b3c-5bef-4f29-bfce-4d784c8aa20d)
![Screenshot_20230714-092155_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/d83bda63-5ff1-4334-a6ea-030ccfb69e2f)
![Screenshot_20230714-092205_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/6759f24b-54ab-45ee-8d72-778100a6ec41)
![Screenshot_20230714-092212_ZArchiver](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/964d4dff-5c6b-4b26-8ce0-419bb23ead44)

**Comment by hedgehog67** [comment]
Yes VDLC work
