### ISSUE TITLE
Crashes when starting the game

### ISSUE THREAD

**Issue by LuigiStar12** [SRB2-Mobile/SRB2-Android#40]
When I opened SRB2 it asked me for access to the storage and so far so good, but while it started it closed. I already deleted the data and it continues the same.

 _I don't know if it's because my phone is 32-bit._

**Comment by bitten2up** [comment]
#37

**Comment by LuigiStar12** [comment]
> #37

Thank you so much! It didn't crash, and for now it's going pretty well.
