### ISSUE TITLE
3d models modern sonic,mario,luigi

### ISSUE THREAD

**Issue by Trapezanidou** [SRB2-Mobile/SRB2-Android#42]
My models doesn't work on vdlc please ive try to replace models.dat on the android apk but still doesn't work please help

**Comment by hedgehog67** [comment]
I think it's better not to change the models.dat because the models turn back to Sprites

**Comment by hedgehog67** [comment]
And also the VDLC models look like this

**Comment by hedgehog67** [comment]
![Screenshot_20230702-110511_Chrome](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/10548a3d-97eb-44ff-8b98-6a89ecb8437c)
![Screenshot_20230702-110457_Chrome](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/0e3e0292-aea2-4bb0-b225-04703709b59e)

**Comment by edotdot** [comment]
Fixed as of 8300649700ba28c33f95deac3e346d460dc3f75e
