### ISSUE TITLE
3D Models

### ISSUE THREAD

**Issue by Jamkoy9** [SRB2-Mobile/SRB2-Android#43]
Adding Models into the game is very confusing now, as nothing I do works. To add insult to injury, when I finally did get the Models I wanted, they appeared as garbled up messes. And now they just refuse to appear period, only showing sprites even when 3d Models are on. OpenGL is being used by the way. If there is a step by step tutorial on how to add the Models you want, that would be nice because the tutorial they put on the update page doesn't really help. Or, the original method should be added as an alternative way to switch Models. Any of these would help a ton, thanks in advance.

**Comment by bitten2up** [comment]
currently there seems to be a crash when adding them, i have been working on a fix off and on

**Comment by Jamkoy9** [comment]
Ok

**Comment by Jamkoy9** [comment]
Thanks

**Comment by xsm2** [comment]
Custom models work fine in 2.2.12, but you have to use the model packs feature:

> We added a model packs feature, so that you can easily switch between multiple model packs, by typing modelpack "path_to_pack.zip" into the console. To make a model pack, all you need is the models.dat file and the models folder inside of a zip or pk3. Pretty convenient, huh?

**Comment by Jamkoy9** [comment]
The modelpack command isn't working for me.

**Comment by bitten2up** [comment]
you can disable modelpacks with the `usemodelpack` var

**Comment by Jamkoy9** [comment]
It registers as an unknown command.

**Comment by xsm2** [comment]
`usemodelpack` works in 2.2.12. The console sometimes doesn't register the keyboard presses correctly, after entering the command read what you have entered to see if it's correct, if it's not try again until the console works

**Comment by Jamkoy9** [comment]
![Screenshot_20230908_230640_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/110706707/92b9242a-91a1-43c0-a319-ba6273696b5d)
(models.zip is the name of the model pack i want to use.)

**Comment by Jamkoy9** [comment]
![Screenshot_20230908_231213_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/110706707/e9bad112-7f13-4109-a4b2-4f06768cc243)
(Models are on, by the way.)

**Comment by xsm2** [comment]
you have to use `modelpack models.zip`  if you have created a models.zip file in your srb2 folder. If you dont want to use the modelspack feature you have to use `usemodelpack  off`. You are mixing the two commands, thats why it's not working

**Comment by xsm2** [comment]
Also are you in 2.2.12 of this github repo (https://github.com/SRB2-Mobile/SRB2-Android/releases/tag/android-port-build-v2212)???? In 2.2.12 the native resolution option has been fixed and the game should use the complete screen of the phone which is not your case

**Comment by Jamkoy9** [comment]
I've reinstalled the game using the github apk, and the native resolution has been fixed. The modelpack and usemodelpack commands are not registered as unknown commands. The only problem now is that while i can tell the console which modelpack i want to use, the models don't appear, even with models on. What is the exact location i should put the models.zip and models.dat files in the srb2 directory?
![Screenshot_20230909_095519_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/110706707/3b0baf2b-d2b9-4500-b43d-d20241409c02)

**Comment by xsm2** [comment]
The models.zip should be in the Sonic Robo Blast 2 directory, outside of any folder like the addons one (Technically you can put it in a folder if you want, but the command you have to enter will be diferent). The models.dat should be INSIDE the models.zip. The models.zip only should have the models folder and the models.dat inside
![imagen](https://github.com/SRB2-Mobile/SRB2-Android/assets/32161135/b7b7e625-e30a-4658-9f30-6f9f676aebd9)

**Comment by Jamkoy9** [comment]
I'm incredibly happy to report:
![Screenshot_20230909_102131_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/110706707/be4203f6-b156-43c5-9489-ad7706e46b2e)
![Screenshot_20230909_102152_Sonic Robo Blast 2](https://github.com/SRB2-Mobile/SRB2-Android/assets/110706707/f09b307e-89b3-42e9-a53e-d5e02198ee9e)
They work now.
Thank you so much for all your help!

**Comment by Jamkoy9** [comment]
Once again, Thank you for everything!
