### ISSUE TITLE
Messed up model textures

### ISSUE THREAD

**Issue by TordGamingYT** [SRB2-Mobile/SRB2-Android#49]
So I wanted to use some custom model pack but everything is messed up, I tried everything to fix it but nothing works, I think it may be the new "modelpacks" thing
![Screenshot_20230719-145748](https://github.com/SRB2-Mobile/SRB2-Android/assets/104328319/39279780-6da7-4478-88e2-4bb86f12ea84)

**Comment by Rafanimatronic** [comment]
https://m.youtube.com/watch?v=CC3sLwb2En8&feature=youtu.be
