### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by TheSTSGang1996** [SRB2-Mobile/SRB2-Android#50]
When I launched SRB2 on my tablet, it just crashes for no reason, I tried force stopping it and still it didn't work, turning of permissions and turning them back on didn't work as well, nothing worked.

**Comment by bitten2up** [comment]
#37

**Comment by TheSTSGang1996** [comment]
Ok thx

**Comment by TheSTSGang1996** [comment]
Gonna see if it works

**Comment by TheSTSGang1996** [comment]
I forgot to say it worked, thanks for the new build. :)
