### ISSUE TITLE
Redmi 9A Game Crash

### ISSUE THREAD

**Issue by Deskarpion** [SRB2-Mobile/SRB2-Android#53]
I used the latest version of the game, when the download was over the game crashed, I downloaded patch 1 and it did not help

**Comment by bitten2up** [comment]
try downloading [this](https://github.com/SRB2-Mobile/SRB2-Android/actions/runs/5490885716), and install the debug build within the zip

**Comment by Deskarpion** [comment]
> попробуйте загрузить [это](https://github.com/SRB2-Mobile/SRB2-Android/actions/runs/5490885716) и установить отладочную сборку в zip-архиве.

srb2.pk3 not found or not vaild

**Comment by Deskarpion** [comment]
> try downloading [this](https://github.com/SRB2-Mobile/SRB2-Android/actions/runs/5490885716), and install the debug build within the zip

srb2.pk3 not found or not vaild
