### ISSUE TITLE
sloperollangle not working correctly with models on

### ISSUE THREAD

**Issue by xsm2** [SRB2-Mobile/SRB2-Android#58]
The [sloperollangle](https://mb.srb2.org/threads/sloperollangle-character-rotation-on-slopes.27164/) is an addon that makes the character change angle when in slopes. the addon works fine when using sprites but it's bugged when using the models, as the inclination of the characters is the inverse of what should be, the models are inclined against the slopes no perpendicular to them

It could be a bug with R_PointToAngle but i'm not sure

This is the windows version of SRB2 2.2.13 and it's how the game should look:
![53-11-23-145337](https://github.com/SRB2-Mobile/SRB2-Android/assets/32161135/e0b46b17-e088-4cc3-9bc1-91af559221f9)
This is how it looks currently in the 2.2.13 android port:
![Screenshot_2023-09-11-14-51-37-871_org stjr srb2](https://github.com/SRB2-Mobile/SRB2-Android/assets/32161135/6b246ba6-810e-42bd-95c6-a69424bcdb96)

**Comment by bitten2up** [comment]
hmm, i honestly wonder if this is related to the upside down models in my prerelease builds, if i find a fix for that, ill see if it also applies here

**Comment by bitten2up** [comment]
might be related

https://github.com/SRB2-Mobile/SRB2-Android/assets/55027142/8977f40f-1aa6-4640-b259-194460f68523
