### ISSUE TITLE
Issue with netgames

### ISSUE THREAD

**Issue by bitten2up** [SRB2-Mobile/SRB2-Android#59]
you are unable to join servers on 2.2.13, happens on 312dc027d33b0ba811dcaa7483b30b093e253627 as well so 0a8346acd36a876db17e48ca0626f56b44baaff5 is not the problem
edit: i haven't tested any commits before 312dc027d33b0ba811dcaa7483b30b093e25362

**Comment by yipeeXDw** [comment]
Hope their fix that on 2.2.14
