### ISSUE TITLE
I cant add 3d models to 2.2.13

### ISSUE THREAD

**Issue by Idk1245** [SRB2-Mobile/SRB2-Android#72]
So I've tried to add models using commands like for example:
modelpack "modelpacks/example.zip"  or
modelpack "storage/emulated/0/Android/data/com.stjr.srb2/files/modelpacks/example.zip"

It also sometimes gives me an error message saying "error while loading modelpacks/example.zip

**Comment by Idk1245** [comment]
I found the old way better in my opinion

**Comment by bitten2up** [comment]
disregard that LMAO

**Comment by Idk1245** [comment]
> disregard that LMAO

Ur repository uses the old way its way easier

**Comment by bitten2up** [comment]
also the models should be in `"/storage/emulated/0/Sonic Robo Blast 2"`

**Comment by Idk1245** [comment]
Yo it works thanks
