### ISSUE TITLE
2D broken for some reason 

### ISSUE THREAD

**Issue by hedgehog67** [SRB2-Mobile/SRB2-Android#83]
I was going to enter something zone in oldc when I entered I saw this
![srb20001](https://github.com/SRB2-Mobile/SRB2-Android/assets/136974893/813b946d-1cd5-4bb7-86a7-c72d6ae5e656)

**Comment by hedgehog67** [comment]
Oldc 2021 round 2 Specifically

**Comment by bitten2up** [comment]
known, not an issue with the mobile port

**Comment by hedgehog67** [comment]
Oh ok
